package com.chatcontroll.app.crypto

import android.content.Context
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey
import com.chatcontroll.app.domain.repository.KeyPair
import com.chatcontroll.app.domain.repository.SessionKeys
import dagger.hilt.android.qualifiers.ApplicationContext
import java.security.Signature
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Manages cryptographic key material lifecycle.
 *
 * - Identity keys are generated by [CryptoEngine] and stored in EncryptedSharedPreferences
 *   (backed by Android Keystore master key).
 * - Session keys are cached in memory only; re-established on app restart.
 * - The SQLCipher database encryption key is stored in Android Keystore.
 */
@Singleton
class KeyManager @Inject constructor(
    @ApplicationContext private val context: Context,
) {
    private val masterKey = MasterKey.Builder(context)
        .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
        .build()

    private val encryptedPrefs by lazy {
        EncryptedSharedPreferences.create(
            context,
            PREFS_FILE,
            masterKey,
            EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
            EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM,
        )
    }

    private val sessionCache = mutableMapOf<String, SessionKeys>()

    fun hasIdentity(): Boolean {
        return encryptedPrefs.contains(KEY_PUBLIC_SIGNING)
    }

    fun storeIdentityKeyPair(keyPair: KeyPair) {
        encryptedPrefs.edit()
            .putString(KEY_PUBLIC_SIGNING, keyPair.publicSigningKey.toHex())
            .putString(KEY_PRIVATE_SIGNING, keyPair.privateSigningKey.toHex())
            .putString(KEY_PUBLIC_IDENTITY, keyPair.publicIdentityKey.toHex())
            .putString(KEY_PRIVATE_IDENTITY, keyPair.privateIdentityKey.toHex())
            .apply()
    }

    fun storePqcKeys(encapsulationKey: ByteArray, decapsulationKey: ByteArray) {
        encryptedPrefs.edit()
            .putString(KEY_PQC_ENCAPSULATION, encapsulationKey.toHex())
            .putString(KEY_PQC_DECAPSULATION, decapsulationKey.toHex())
            .apply()
    }

    fun getPqcEncapsulationKey(): ByteArray? {
        return encryptedPrefs.getString(KEY_PQC_ENCAPSULATION, null)?.hexToBytes()
    }

    fun getPqcDecapsulationKey(): ByteArray? {
        return encryptedPrefs.getString(KEY_PQC_DECAPSULATION, null)?.hexToBytes()
    }

    fun loadIdentityKeyPair(): KeyPair? {
        val pubSign = encryptedPrefs.getString(KEY_PUBLIC_SIGNING, null)?.hexToBytes() ?: return null
        val privSign = encryptedPrefs.getString(KEY_PRIVATE_SIGNING, null)?.hexToBytes() ?: return null
        val pubId = encryptedPrefs.getString(KEY_PUBLIC_IDENTITY, null)?.hexToBytes() ?: return null
        val privId = encryptedPrefs.getString(KEY_PRIVATE_IDENTITY, null)?.hexToBytes() ?: return null
        return KeyPair(pubSign, privSign, pubId, privId)
    }

    fun storeUserId(userId: String) {
        encryptedPrefs.edit().putString(KEY_USER_ID, userId).apply()
    }

    fun getUserId(): String? {
        return encryptedPrefs.getString(KEY_USER_ID, null)
    }

    fun storeShareCode(shareCode: String) {
        encryptedPrefs.edit().putString(KEY_SHARE_CODE, shareCode).apply()
    }

    fun getShareCode(): String? {
        return encryptedPrefs.getString(KEY_SHARE_CODE, null)
    }

    fun cacheSessionKeys(peerId: String, sessionKeys: SessionKeys) {
        sessionCache[peerId] = sessionKeys
    }

    fun getCachedSessionKeys(peerId: String): SessionKeys? {
        return sessionCache[peerId]
    }

    fun clearSessionCache() {
        sessionCache.clear()
    }

    /**
     * Get or create the SQLCipher database encryption key.
     *
     * Android Keystore keys cannot be exported (encoded returns null),
     * so we generate a random key and store it in EncryptedSharedPreferences
     * which is itself protected by an Android Keystore master key.
     */
    fun getDatabaseKey(): ByteArray {
        val existing = encryptedPrefs.getString(KEY_DB_PASSPHRASE, null)
        if (existing != null) {
            return existing.hexToBytes()
        }
        val key = ByteArray(32).also { java.security.SecureRandom().nextBytes(it) }
        encryptedPrefs.edit().putString(KEY_DB_PASSPHRASE, key.toHex()).apply()
        return key
    }

    fun sign(data: ByteArray): ByteArray {
        val privKeyBytes = encryptedPrefs.getString(KEY_PRIVATE_SIGNING, null)?.hexToBytes()
            ?: throw IllegalStateException("No signing key available")
        val kf = java.security.KeyFactory.getInstance("Ed25519", "BC")
        val privKey = kf.generatePrivate(java.security.spec.PKCS8EncodedKeySpec(privKeyBytes))
        val sig = Signature.getInstance("Ed25519", "BC")
        sig.initSign(privKey)
        sig.update(data)
        return sig.sign()
    }

    fun wipeAll() {
        encryptedPrefs.edit().clear().apply()
        sessionCache.clear()
    }

    companion object {
        private const val PREFS_FILE = "chatcontroll_keys"
        private const val KEY_DB_PASSPHRASE = "db_passphrase"
        private const val KEY_PUBLIC_SIGNING = "pub_sign"
        private const val KEY_PRIVATE_SIGNING = "priv_sign"
        private const val KEY_PUBLIC_IDENTITY = "pub_id"
        private const val KEY_PRIVATE_IDENTITY = "priv_id"
        private const val KEY_USER_ID = "user_id"
        private const val KEY_SHARE_CODE = "share_code"
        private const val KEY_PQC_ENCAPSULATION = "pqc_ek"
        private const val KEY_PQC_DECAPSULATION = "pqc_dk"
    }
}

private fun ByteArray.toHex(): String = joinToString("") { "%02x".format(it) }

private fun String.hexToBytes(): ByteArray {
    check(length % 2 == 0) { "Hex string must have even length" }
    return chunked(2).map { it.toInt(16).toByte() }.toByteArray()
}
