package com.chatcontroll.app.crypto

import android.content.Context
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey
import com.chatcontroll.app.domain.repository.KeyPair
import com.chatcontroll.app.domain.repository.SessionKeys
import dagger.hilt.android.qualifiers.ApplicationContext
import java.security.Signature
import java.util.concurrent.ConcurrentHashMap
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Manages cryptographic key material lifecycle.
 *
 * - Identity keys are generated by [CryptoEngine] and stored in EncryptedSharedPreferences
 *   (backed by Android Keystore master key).
 * - Session keys (including send/receive key material) are persisted in
 *   EncryptedSharedPreferences so they survive app restart.
 * - The SQLCipher database encryption key is stored in EncryptedSharedPreferences
 *   (backed by Android Keystore master key).
 */
@Singleton
class KeyManager @Inject constructor(
    @ApplicationContext private val context: Context,
) {
    private val masterKey = MasterKey.Builder(context)
        .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
        .build()

    private val encryptedPrefs by lazy {
        EncryptedSharedPreferences.create(
            context,
            PREFS_FILE,
            masterKey,
            EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
            EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM,
        )
    }

    private val sessionCache = ConcurrentHashMap<String, SessionKeys>()

    fun hasIdentity(): Boolean {
        return encryptedPrefs.contains(KEY_USER_ID) &&
            encryptedPrefs.contains(KEY_PUBLIC_SIGNING) &&
            encryptedPrefs.contains(KEY_PRIVATE_SIGNING) &&
            encryptedPrefs.contains(KEY_PUBLIC_IDENTITY) &&
            encryptedPrefs.contains(KEY_PRIVATE_IDENTITY)
    }

    fun storeIdentityKeyPair(keyPair: KeyPair) {
        encryptedPrefs.edit()
            .putString(KEY_PUBLIC_SIGNING, keyPair.publicSigningKey.toHex())
            .putString(KEY_PRIVATE_SIGNING, keyPair.privateSigningKey.toHex())
            .putString(KEY_PUBLIC_IDENTITY, keyPair.publicIdentityKey.toHex())
            .putString(KEY_PRIVATE_IDENTITY, keyPair.privateIdentityKey.toHex())
            .apply()
    }

    fun storePqcKeys(encapsulationKey: ByteArray, decapsulationKey: ByteArray) {
        encryptedPrefs.edit()
            .putString(KEY_PQC_ENCAPSULATION, encapsulationKey.toHex())
            .putString(KEY_PQC_DECAPSULATION, decapsulationKey.toHex())
            .apply()
    }

    fun getPqcEncapsulationKey(): ByteArray? {
        return encryptedPrefs.getString(KEY_PQC_ENCAPSULATION, null)?.hexToBytes()
    }

    fun getPqcDecapsulationKey(): ByteArray? {
        return encryptedPrefs.getString(KEY_PQC_DECAPSULATION, null)?.hexToBytes()
    }

    fun loadIdentityKeyPair(): KeyPair? {
        val pubSign = encryptedPrefs.getString(KEY_PUBLIC_SIGNING, null)?.hexToBytes() ?: return null
        val privSign = encryptedPrefs.getString(KEY_PRIVATE_SIGNING, null)?.hexToBytes() ?: return null
        val pubId = encryptedPrefs.getString(KEY_PUBLIC_IDENTITY, null)?.hexToBytes() ?: return null
        val privId = encryptedPrefs.getString(KEY_PRIVATE_IDENTITY, null)?.hexToBytes() ?: return null
        return KeyPair(pubSign, privSign, pubId, privId)
    }

    fun storeUserId(userId: String) {
        encryptedPrefs.edit().putString(KEY_USER_ID, userId).apply()
    }

    fun getUserId(): String? {
        return encryptedPrefs.getString(KEY_USER_ID, null)
    }

    fun storeShareCode(shareCode: String) {
        encryptedPrefs.edit().putString(KEY_SHARE_CODE, shareCode).apply()
    }

    fun getShareCode(): String? {
        return encryptedPrefs.getString(KEY_SHARE_CODE, null)
    }

    fun storeCreatedAt(epochMillis: Long) {
        encryptedPrefs.edit().putLong(KEY_CREATED_AT, epochMillis).apply()
    }

    fun getCreatedAt(): Long {
        return encryptedPrefs.getLong(KEY_CREATED_AT, 0L)
    }

    fun cacheSessionKeys(peerId: String, sessionKeys: SessionKeys) {
        sessionCache[peerId] = sessionKeys
        // Persist session mapping AND key material so they survive app restarts.
        // The ratchet state is persisted separately via saveRatchetState().
        // Send/receive keys are needed by CallManager to derive call-specific keys
        // without re-establishing the session (which would overwrite ratchet state).
        val editor = encryptedPrefs.edit()
            .putString(SESSION_PREFIX + peerId, sessionKeys.sessionId)
            .putBoolean(PQC_PREFIX + peerId, sessionKeys.pqcEstablished)
        if (sessionKeys.sendKey.isNotEmpty()) {
            editor.putString(SEND_KEY_PREFIX + peerId, sessionKeys.sendKey.toHex())
        }
        if (sessionKeys.receiveKey.isNotEmpty()) {
            editor.putString(RECV_KEY_PREFIX + peerId, sessionKeys.receiveKey.toHex())
        }
        editor.apply()
    }

    fun isPeerPqcEstablished(peerId: String): Boolean {
        return sessionCache[peerId]?.pqcEstablished
            ?: encryptedPrefs.getBoolean(PQC_PREFIX + peerId, false)
    }

    fun getCachedSessionKeys(peerId: String): SessionKeys? {
        sessionCache[peerId]?.let { return it }
        // Restore from persistent storage after app restart
        val sessionId = encryptedPrefs.getString(SESSION_PREFIX + peerId, null) ?: return null
        val pqc = encryptedPrefs.getBoolean(PQC_PREFIX + peerId, false)
        val sendKey = encryptedPrefs.getString(SEND_KEY_PREFIX + peerId, null)?.hexToBytes()
            ?: ByteArray(0)
        val recvKey = encryptedPrefs.getString(RECV_KEY_PREFIX + peerId, null)?.hexToBytes()
            ?: ByteArray(0)
        val restored = SessionKeys(
            sendKey = sendKey,
            receiveKey = recvKey,
            sessionId = sessionId,
            pqcEstablished = pqc,
        )
        sessionCache[peerId] = restored
        return restored
    }

    fun clearSessionForPeer(peerId: String) {
        val sessionId = sessionCache.remove(peerId)?.sessionId
            ?: encryptedPrefs.getString(SESSION_PREFIX + peerId, null)
        encryptedPrefs.edit()
            .remove(SESSION_PREFIX + peerId)
            .remove(SEND_KEY_PREFIX + peerId)
            .remove(RECV_KEY_PREFIX + peerId)
            .remove(PQC_PREFIX + peerId)
            .apply()
        if (sessionId != null) {
            removeRatchetState(sessionId)
        }
    }

    fun clearSessionCache() {
        sessionCache.clear()
        // Also remove persisted session keys so getCachedSessionKeys()
        // doesn't restore stale material after key rotation.
        val editor = encryptedPrefs.edit()
        encryptedPrefs.all.keys.filter {
            it.startsWith(SESSION_PREFIX) ||
            it.startsWith(SEND_KEY_PREFIX) ||
            it.startsWith(RECV_KEY_PREFIX) ||
            it.startsWith(PQC_PREFIX)
        }.forEach { editor.remove(it) }
        editor.apply()
    }

    /**
     * Get or create the SQLCipher database encryption key.
     *
     * Android Keystore keys cannot be exported (encoded returns null),
     * so we generate a random key and store it in EncryptedSharedPreferences
     * which is itself protected by an Android Keystore master key.
     */
    fun getDatabaseKey(): ByteArray {
        val existing = encryptedPrefs.getString(KEY_DB_PASSPHRASE, null)
        if (existing != null) {
            return existing.hexToBytes()
        }
        val key = ByteArray(32).also { java.security.SecureRandom().nextBytes(it) }
        encryptedPrefs.edit().putString(KEY_DB_PASSPHRASE, key.toHex()).apply()
        return key
    }

    fun sign(data: ByteArray): ByteArray {
        val privKeyBytes = encryptedPrefs.getString(KEY_PRIVATE_SIGNING, null)?.hexToBytes()
            ?: throw IllegalStateException("No signing key available")
        val kf = java.security.KeyFactory.getInstance("Ed25519", "BC")
        val privKey = kf.generatePrivate(java.security.spec.PKCS8EncodedKeySpec(privKeyBytes))
        val sig = Signature.getInstance("Ed25519", "BC")
        sig.initSign(privKey)
        sig.update(data)
        return sig.sign()
    }

    fun saveRatchetState(sessionId: String, serialized: String) {
        encryptedPrefs.edit().putString(RATCHET_PREFIX + sessionId, serialized).apply()
    }

    fun loadRatchetState(sessionId: String): String? {
        return encryptedPrefs.getString(RATCHET_PREFIX + sessionId, null)
    }

    fun removeRatchetState(sessionId: String) {
        encryptedPrefs.edit().remove(RATCHET_PREFIX + sessionId).apply()
    }

    fun removeAllRatchetStates() {
        val editor = encryptedPrefs.edit()
        encryptedPrefs.all.keys
            .filter { it.startsWith(RATCHET_PREFIX) }
            .forEach { editor.remove(it) }
        editor.apply()
    }

    // ── Staged key rotation (crash-safe) ──────────────────────────────

    /**
     * Stage new identity keys before the server call.
     * If the server accepts, call [promoteStagedKeys] to make them active.
     * If the server rejects or the call fails, call [clearStagedKeys].
     */
    fun stageIdentityKeyPair(keyPair: KeyPair) {
        encryptedPrefs.edit()
            .putString(PENDING_PUBLIC_SIGNING, keyPair.publicSigningKey.toHex())
            .putString(PENDING_PRIVATE_SIGNING, keyPair.privateSigningKey.toHex())
            .putString(PENDING_PUBLIC_IDENTITY, keyPair.publicIdentityKey.toHex())
            .putString(PENDING_PRIVATE_IDENTITY, keyPair.privateIdentityKey.toHex())
            .apply()
    }

    fun stagePqcKeys(encapsulationKey: ByteArray, decapsulationKey: ByteArray) {
        encryptedPrefs.edit()
            .putString(PENDING_PQC_ENCAPSULATION, encapsulationKey.toHex())
            .putString(PENDING_PQC_DECAPSULATION, decapsulationKey.toHex())
            .apply()
    }

    /**
     * Promote staged keys to active. Called after server confirms rotation,
     * or on app startup if staged keys exist (server accepted but app crashed
     * before promotion).
     */
    fun promoteStagedKeys() {
        val pubSign = encryptedPrefs.getString(PENDING_PUBLIC_SIGNING, null) ?: return
        val privSign = encryptedPrefs.getString(PENDING_PRIVATE_SIGNING, null) ?: return
        val pubId = encryptedPrefs.getString(PENDING_PUBLIC_IDENTITY, null) ?: return
        val privId = encryptedPrefs.getString(PENDING_PRIVATE_IDENTITY, null) ?: return

        val editor = encryptedPrefs.edit()
            .putString(KEY_PUBLIC_SIGNING, pubSign)
            .putString(KEY_PRIVATE_SIGNING, privSign)
            .putString(KEY_PUBLIC_IDENTITY, pubId)
            .putString(KEY_PRIVATE_IDENTITY, privId)

        // Promote PQC keys if staged
        val pqcEk = encryptedPrefs.getString(PENDING_PQC_ENCAPSULATION, null)
        val pqcDk = encryptedPrefs.getString(PENDING_PQC_DECAPSULATION, null)
        if (pqcEk != null && pqcDk != null) {
            editor.putString(KEY_PQC_ENCAPSULATION, pqcEk)
            editor.putString(KEY_PQC_DECAPSULATION, pqcDk)
        }

        // Clear staged keys and commit synchronously for crash safety.
        // This is the crash-recovery path — apply() could lose data if the
        // process dies between return and the async disk write.
        editor
            .remove(PENDING_PUBLIC_SIGNING)
            .remove(PENDING_PRIVATE_SIGNING)
            .remove(PENDING_PUBLIC_IDENTITY)
            .remove(PENDING_PRIVATE_IDENTITY)
            .remove(PENDING_PQC_ENCAPSULATION)
            .remove(PENDING_PQC_DECAPSULATION)
            .commit()
    }

    fun hasStagedKeys(): Boolean {
        return encryptedPrefs.contains(PENDING_PUBLIC_SIGNING)
    }

    fun clearStagedKeys() {
        encryptedPrefs.edit()
            .remove(PENDING_PUBLIC_SIGNING)
            .remove(PENDING_PRIVATE_SIGNING)
            .remove(PENDING_PUBLIC_IDENTITY)
            .remove(PENDING_PRIVATE_IDENTITY)
            .remove(PENDING_PQC_ENCAPSULATION)
            .remove(PENDING_PQC_DECAPSULATION)
            .apply()
    }

    fun wipeAll() {
        encryptedPrefs.edit().clear().apply()
        sessionCache.clear()
    }

    companion object {
        private const val PREFS_FILE = "chatcontroll_keys"
        private const val KEY_DB_PASSPHRASE = "db_passphrase"
        private const val KEY_PUBLIC_SIGNING = "pub_sign"
        private const val KEY_PRIVATE_SIGNING = "priv_sign"
        private const val KEY_PUBLIC_IDENTITY = "pub_id"
        private const val KEY_PRIVATE_IDENTITY = "priv_id"
        private const val KEY_USER_ID = "user_id"
        private const val KEY_SHARE_CODE = "share_code"
        private const val KEY_PQC_ENCAPSULATION = "pqc_ek"
        private const val KEY_PQC_DECAPSULATION = "pqc_dk"
        private const val KEY_CREATED_AT = "created_at"
        private const val PQC_PREFIX = "pqc_session_"
        private const val SESSION_PREFIX = "session_id_"
        private const val SEND_KEY_PREFIX = "session_sk_"
        private const val RECV_KEY_PREFIX = "session_rk_"
        private const val RATCHET_PREFIX = "ratchet_"
        private const val PENDING_PUBLIC_SIGNING = "pending_pub_sign"
        private const val PENDING_PRIVATE_SIGNING = "pending_priv_sign"
        private const val PENDING_PUBLIC_IDENTITY = "pending_pub_id"
        private const val PENDING_PRIVATE_IDENTITY = "pending_priv_id"
        private const val PENDING_PQC_ENCAPSULATION = "pending_pqc_ek"
        private const val PENDING_PQC_DECAPSULATION = "pending_pqc_dk"
    }
}

private fun ByteArray.toHex(): String = joinToString("") { "%02x".format(it) }

private fun String.hexToBytes(): ByteArray {
    check(length % 2 == 0) { "Hex string must have even length" }
    return chunked(2).map { it.toInt(16).toByte() }.toByteArray()
}
